variables:
  major: 1
  minor: 0
trigger:
  branches:
    include:
      - main
      - Release-*
      - V-*
      - Feature-*
      - US-*
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage:
    displayName: Build_Feature_Version_Number
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/V-1.0')
    jobs:
      - job: Build_Feature_Version_Number
        variables:
          patch: $[counter(variables['minor'], 0)]
        steps:
          - bash: |
              echo "##vso[build.updatebuildnumber]GT-$(Build.SourceBranchName)-$(Build.BuildID)"
            name: SetFeatureBuildName
  - stage:
    displayName: Build_Release_Version_Number
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/v-1.0')
    jobs:
      - job: Build_Release_Version_Number
        variables:
          patch: $[counter(variables['minor'], 0)]
        steps:
          - bash: |
              echo "##vso[build.updatebuildnumber]$(major).$(minor).$(patch)"
            name: SetMasterBuildName
  - stage: CI
    displayName: Build Project
    condition: always()
    jobs:
      - job: build
        displayName: 'Build and Test'
        steps:
          - script: echo "Building and testing the project..."
            displayName: 'Run build script'
          - task: CreateWorkItem@2
            inputs:
              teamProject: 'Initiatives'
              workItemType: 'User Story'
              title: 'Test Build $(Build.BuildNumber)'
              assignedTo: 'baylee hillmer <baylee.hillmer@goodland.tech>'
              areaPath: 'Initiatives\Operations'
              iterationPath: 'Red Team@currentIteration'
              fieldMappings: |
                Description=<div>This user story was automatically generated by the system following the successful build of: <div><br></div> <ul><li>Build Number: $(Build.BuildNumber).</li></ul><br> The QA team is responsible for testing this build and validating all related bugs and user stories. Please ensure all functionalities meet the expected behavior.</div><div><br> </div><div><a href="https://dev.azure.com/goodlandTech/Initiatives/_traceability/runview/workitems?currentRunId=$(Build.BuildNumber)"></a> </div><div><a href="https://dev.azure.com/goodlandTech/Initiatives/_traceability/runview/workitems?currentRunId=$(Build.BuildId)">https://dev.azure.com/goodlandTech/Initiatives/_traceability/runview/workitems?currentRunId=$(Build.BuildId)</a> </div><div><br> </div><div><br> </div>
                Tags=QA Build
                Value area=Operational
                Acceptance Criteria=<div><ul><li>All work items linked under &quot;'Test Build $(Build.BuildNumber)&quot; have been tested. </li><li>All time spent testing has been added to the relevant work item.</li> </ul> </div>
              associate: true
              associationType: 'integratedInBuild'
              linkWorkItems: true
              linkType: 'Related'
              linkTarget: 'associate'
              linkPR: true
              authType: 'internal'